// #include "../../../../../inc/MarlinConfigPre.h"
// #if ENABLED(BTT_UI_SPI)
// #include "../TSC_Menu.h"

// #include "SendGcode.h"

// #define LCD_WIDTH   LCD_WIDTH_PIXEL
// #define LCD_HEIGHT  LCD_HEIGHT_PIXEL

// /*about GCODE KEY*/
// #define GKEY_WIDTH        (LCD_WIDTH/6)
// #define GKEY_HEIGHT       ((LCD_HEIGHT - 50)/4)

// typedef enum
// {
//   SOFT_KEY_123 = 0,
//   SOFT_KEY_ABC,
// }SOFT_KEY_TYPE;

// // 26 buttons
// const GUI_RECT rect_of_Gkey[]={
//   {0*GKEY_WIDTH, 0*GKEY_HEIGHT+ICON_START_Y, 1*GKEY_WIDTH, 1*GKEY_HEIGHT+ICON_START_Y},
//   {1*GKEY_WIDTH, 0*GKEY_HEIGHT+ICON_START_Y, 2*GKEY_WIDTH, 1*GKEY_HEIGHT+ICON_START_Y},
//   {2*GKEY_WIDTH, 0*GKEY_HEIGHT+ICON_START_Y, 3*GKEY_WIDTH, 1*GKEY_HEIGHT+ICON_START_Y},
//   {3*GKEY_WIDTH, 0*GKEY_HEIGHT+ICON_START_Y, 4*GKEY_WIDTH, 1*GKEY_HEIGHT+ICON_START_Y},
//   {4*GKEY_WIDTH, 0*GKEY_HEIGHT+ICON_START_Y, 5*GKEY_WIDTH, 1*GKEY_HEIGHT+ICON_START_Y},
//   {5*GKEY_WIDTH, 0*GKEY_HEIGHT+ICON_START_Y, 6*GKEY_WIDTH, 1*GKEY_HEIGHT+ICON_START_Y}, // Del

//   {0*GKEY_WIDTH, 1*GKEY_HEIGHT+ICON_START_Y, 1*GKEY_WIDTH, 2*GKEY_HEIGHT+ICON_START_Y},
//   {1*GKEY_WIDTH, 1*GKEY_HEIGHT+ICON_START_Y, 2*GKEY_WIDTH, 2*GKEY_HEIGHT+ICON_START_Y},
//   {2*GKEY_WIDTH, 1*GKEY_HEIGHT+ICON_START_Y, 3*GKEY_WIDTH, 2*GKEY_HEIGHT+ICON_START_Y},
//   {3*GKEY_WIDTH, 1*GKEY_HEIGHT+ICON_START_Y, 4*GKEY_WIDTH, 2*GKEY_HEIGHT+ICON_START_Y},
//   {4*GKEY_WIDTH, 1*GKEY_HEIGHT+ICON_START_Y, 5*GKEY_WIDTH, 2*GKEY_HEIGHT+ICON_START_Y},
//   {5*GKEY_WIDTH, 1*GKEY_HEIGHT+ICON_START_Y, 6*GKEY_WIDTH, 2*GKEY_HEIGHT+ICON_START_Y}, // Space

//   {0*GKEY_WIDTH, 2*GKEY_HEIGHT+ICON_START_Y, 1*GKEY_WIDTH, 3*GKEY_HEIGHT+ICON_START_Y},
//   {1*GKEY_WIDTH, 2*GKEY_HEIGHT+ICON_START_Y, 2*GKEY_WIDTH, 3*GKEY_HEIGHT+ICON_START_Y},
//   {2*GKEY_WIDTH, 2*GKEY_HEIGHT+ICON_START_Y, 3*GKEY_WIDTH, 3*GKEY_HEIGHT+ICON_START_Y},
//   {3*GKEY_WIDTH, 2*GKEY_HEIGHT+ICON_START_Y, 4*GKEY_WIDTH, 3*GKEY_HEIGHT+ICON_START_Y},
//   {4*GKEY_WIDTH, 2*GKEY_HEIGHT+ICON_START_Y, 5*GKEY_WIDTH, 3*GKEY_HEIGHT+ICON_START_Y},
//   {5*GKEY_WIDTH, 2*GKEY_HEIGHT+ICON_START_Y, 6*GKEY_WIDTH, 3*GKEY_HEIGHT+ICON_START_Y}, // ABC to 123

//   {0*GKEY_WIDTH, 3*GKEY_HEIGHT+ICON_START_Y, 1*GKEY_WIDTH, 4*GKEY_HEIGHT+ICON_START_Y},
//   {1*GKEY_WIDTH, 3*GKEY_HEIGHT+ICON_START_Y, 2*GKEY_WIDTH, 4*GKEY_HEIGHT+ICON_START_Y},
//   {2*GKEY_WIDTH, 3*GKEY_HEIGHT+ICON_START_Y, 3*GKEY_WIDTH, 4*GKEY_HEIGHT+ICON_START_Y},
//   {3*GKEY_WIDTH, 3*GKEY_HEIGHT+ICON_START_Y, 4*GKEY_WIDTH, 4*GKEY_HEIGHT+ICON_START_Y},
//   {4*GKEY_WIDTH, 3*GKEY_HEIGHT+ICON_START_Y, 5*GKEY_WIDTH, 4*GKEY_HEIGHT+ICON_START_Y},
//   {5*GKEY_WIDTH, 3*GKEY_HEIGHT+ICON_START_Y, 6*GKEY_WIDTH, 4*GKEY_HEIGHT+ICON_START_Y},

//   // Back
//   {0*GKEY_WIDTH+5, 0*GKEY_HEIGHT+5,  1*GKEY_WIDTH-5, ICON_START_Y-5},
//   // Send
//   {5*GKEY_WIDTH+5, 0*GKEY_HEIGHT+5,  6*GKEY_WIDTH-5, ICON_START_Y-5},
// };

// const char * const softKeyValue[][26] = {
//   {
//     "1", "2", "3", "M", "G", "Del",
//     "4", "5", "6", "X", "Y", "Space",
//     "7", "8", "9", "Z", "E", "ABC",
//     ".", "0", "-", "S", "T", " ",
//     "Back", "Send",
//   },
//   {
//     "A", "B", "C", "D", "F", "Del",
//     "H", "I", "J", "K", "L", "Space",
//     "N", "O", "P", "Q", "R", "123",
//     "U", "V", "W", " ", " ", " ",
//     "Back", "Send",
//   }
// };

// SOFT_KEY_TYPE softKeyType = SOFT_KEY_123;

// #endif

